version: "3.8"
services:
  mongo1:
    image: mongo:5
    container_name: mongo1
    networks:
      mongoCluster:
    entrypoint: ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "localhost,mongo1"]
    ports:
      - 27017:27017
    volumes:
      - mongo1-data:/data/db

  mongo2:
    image: mongo:5
    container_name: mongo2
    networks:
      mongoCluster:
    entrypoint: ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "localhost,mongo2"]
    ports:
      - 27018:27017
    volumes:
      - mongo2-data:/data/db


  mongo3:
    image: mongo:5
    container_name: mongo3
    networks:
      mongoCluster:
    entrypoint: ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "localhost,mongo3"]
    ports:
      - 27019:27017
    volumes:
      - mongo3-data:/data/db


  yoloapp:
    image: 352708296901.dkr.ecr.eu-central-1.amazonaws.com/tamirmarz-repo:yolo
    container_name: yoloapp
    networks:
      mongoCluster:
    ports:
      - "8081:8081"
    secrets:
      - bucket
      - client
    environment:
      - BUCKET_NAME=/run/secrets/bucket_name
      - MONGO_CLIENT=/run/secrets/mongo_client


  polybot:
    image: 352708296901.dkr.ecr.eu-central-1.amazonaws.com/tamirmarz-repo:polybot
    container_name: bot
    networks:
      mongoCluster:
    ports:
      - "8443:8443"
    secrets:
      - token
      - url
    environment:
      - TELEGRAM_TOKEN=/run/secrets/telegram_token
      - TELEGRAM_APP_URL=/run/secrets/telegram_url


networks:
  mongoCluster:

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:

secrets:
  token:
    file: ./telegram_token
  url:
    file: ./telegram_url
  client:
    file: ./mongo_client
  bucket:
    file: ./bucket_name



